# config/database.yml
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: rails_from_scratch_development

test:
  <<: *default
  database: rails_from_scratch_test

production:
  <<: *default
  database: rails_from_scratch
  username: rails_from_scratch
  password: <%= ENV['RAILS_FROM_SCRATCH_DATABASE_PASSWORD'] %>
