name: 'Run Specs'
on:
  push:
    branches:
      - master
jobs:
  build:
    name: 'Test Suite'
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.2-alpine
        env:
          POSTGRES_PASSWORD: secret
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Ruby 2.7'
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: 'Cache Rubygems'
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: 'Cache Yarn'
        uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: 'Setup App'
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: secret
          RAILS_ENV: test
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bin/rails db:setup
          yarn

      - name: 'Run Tests'
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: secret
          RAILS_ENV: test
        run: |
          bundle exec rspec